- icon: fas fa-home
  title: Heladería
  description: De toda la ciudad de Pitalito, en Yogú encuentras un sabor único. Cada mes podrás probar otras variedades
        acompañadas del sabor a yogurt, que te aseguramos, no tiene comparación. Nos esforzamos
        para que disfrutes tanto, que siempre querrás volver.

- icon: fas fa-shapes
  title: Juegos
  description: Disponemos diferentes de un buen ambiente y juegos de mesa que harán más amena tu visita o tu paseo turístico a Pitalito. Podrás jugar
        parqués, ajedrez, tangram, dominó o jenga. Si buscas un buen plan para pasar un buen rato, nosotros lo
        tenemos.

- icon: fas fa-motorcycle
  title: Eventos
  description: Escríbenos o llámanos para cumplir tu antojo de un delicioso helado Yogú. Si tienes un evento importante y deseas
        que tus invitados se deleiten con nuestras delicias, solo nos avisas y nosotros nos encargamos.

- icon: fas fa-phone-square
  title: Reservaciones
  description: ¿A qué persona especial deseas invitar? ¿Y es en un horario especial también? Avísanos con anticipación para
        reservarles un lugar y tener preparada la hermosa sorpresa que deseas regalar. O si un grupo de amigos
        necesitan de nuestras instalaciones, nosotros nos encargamos de tener todo listo.